// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxP5jLEiYyL5hTBqPgawsL4XJ6k_VKHd8',
    appId: '1:1011842661481:web:e85b3aa24464e12ae2b6f8',
    messagingSenderId: '1011842661481',
    projectId: 'sincroapp-529cc',
    authDomain: 'sincroapp-529cc.firebaseapp.com',
    storageBucket: 'sincroapp-529cc.firebasestorage.app',
    measurementId: 'G-JVW0L403K9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwM51dLKFbejbJjiRHMN8gTDhfwsTSq10',
    appId: '1:1011842661481:android:9b92388c1210fef2e2b6f8',
    messagingSenderId: '1011842661481',
    projectId: 'sincroapp-529cc',
    storageBucket: 'sincroapp-529cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8nNiVq7uFSsxNQObZ8RyWZV9DuTAea0U',
    appId: '1:1011842661481:ios:464deb5ead6785a4e2b6f8',
    messagingSenderId: '1011842661481',
    projectId: 'sincroapp-529cc',
    storageBucket: 'sincroapp-529cc.firebasestorage.app',
    iosBundleId: 'com.example.sincroAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8nNiVq7uFSsxNQObZ8RyWZV9DuTAea0U',
    appId: '1:1011842661481:ios:464deb5ead6785a4e2b6f8',
    messagingSenderId: '1011842661481',
    projectId: 'sincroapp-529cc',
    storageBucket: 'sincroapp-529cc.firebasestorage.app',
    iosBundleId: 'com.example.sincroAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCibyRlDbOYYg8c5KYThDcdx9xvwoVIy70',
    appId: '1:1011842661481:web:ff5e1ece377ba33ee2b6f8',
    messagingSenderId: '1011842661481',
    projectId: 'sincroapp-529cc',
    authDomain: 'sincroapp-529cc.firebaseapp.com',
    storageBucket: 'sincroapp-529cc.firebasestorage.app',
    measurementId: 'G-FM1P895GBS',
  );
}
